### ISSUE TITLE
wpp:150: attempt to index global wireless (a nil value)

### ISSUE THREAD

**Issue by 2Peti** [jdf221/CC-WirelessPeripheral#1]
When i run this code:

wpp.wireless.host("network-name")

while true do
  local event = {os.pullEvent()}
  wpp.wireless.localEventHandler(event)
end

i get: 
wpp:150: attempt to index global wireless (a nil value)

![image](https://user-images.githubusercontent.com/44583946/105881210-80aeb100-6004-11eb-9379-9e7fe240b8f9.png)

**Comment by jdf221** [comment]
Just updated the file, download the new version and try that. There was an issue after I converted it to use `require`.

**Comment by 2Peti** [comment]
Thanks it works
