### ISSUE TITLE
nil value - index global

### ISSUE THREAD

**Issue by PantACRO4life** [jdf221/CC-WirelessPeripheral#10]
I don't know how to describe the issue so ill just post a few screen.

If you need to know anything please let me know.

![image](https://github.com/jdf221/CC-WirelessPeripheral/assets/6643071/3cc86587-5e57-42f7-b9cd-83a7d2372f86)
![image](https://github.com/jdf221/CC-WirelessPeripheral/assets/6643071/e0124585-5923-439c-8804-a5aa530bef89)

**Comment by jdf221** [comment]
Did you run the command to install/download the "wpp" file?

```
wget https://raw.githubusercontent.com/jdf221/CC-WirelessPeripheral/main/wpp.lua wpp
```

**Comment by PantACRO4life** [comment]
> Did you run the command to install/download the "wpp" file?
> 
> ```
> wget https://raw.githubusercontent.com/jdf221/CC-WirelessPeripheral/main/wpp.lua wpp
> ```

I  did but I found out that it only happen when I type the command "local" in front of the other words

**Comment by PantACRO4life** [comment]
idk if it matter that im on single player but including "local" doesnt work for other script aswell.
MC V: 1.20.1

Im not use to play around with CC, in fact its been a long while. 
What does Local do ?

**Comment by jdf221** [comment]
Are you able to edit a new file and put your code in there? Then run the code by running that file?

Do you need to use local? Try it without it.

**Comment by PantACRO4life** [comment]
> Are you able to edit a new file and put your code in there? Then run the code by running that file?
> 
> Do you need to use local? Try it without it.

it was from manual typing but now doing local does work if its a lua code that run by itself.

I asume its like batch file where some comment are different depending if you run it manually or if you execute a script.

**Comment by jdf221** [comment]
Hope you got it working!

**Comment by PantACRO4life** [comment]
yes I did, I made something great ! thanks
