### ISSUE TITLE
Cant wrap peripherals

### ISSUE THREAD

**Issue by Lautarosco** [jdf221/CC-WirelessPeripheral#11]
Maybe I am doing something wrong, but I cant seem to wrap a peripheral wirelessly.

I can get the wireless peripherals with peripheral.getNames()
![image](https://github.com/jdf221/CC-WirelessPeripheral/assets/69166345/9cb46a79-a751-4830-83b4-b8df6eb14180)

But when using peripheral.wrap I get a nil value (with debugging, I can see that it tries to use a native peripheral since it doesn't find a remote one)

![image](https://github.com/jdf221/CC-WirelessPeripheral/assets/69166345/0589169d-7703-42f2-8d85-bb33fa18749c)

**Comment by jdf221** [comment]
I have to refresh myself on how this thing works every time someone asks a question about this lol.

My immediate thought is that you need to use the full "wpp@" string for the wrap argument, not just the "monitor_0"

That full "peripheral path" is how it knows what computer the real peripheral is connected to. The 5 in the string refers to the computer ID that the peripheral is connected to.

**Comment by Lautarosco** [comment]
Omg can't believe you answered so quicly. You are right, I should use the real string. Was checking it but you answered before I could lol

**Comment by jdf221** [comment]
Haha, the magic of email notifications and the GitHub phone app.

Happy it works for you! I find it so cool that people actually use this random thing I made.
